version: '3.3'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: kartoza/postgis:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=observationmanagementapi
      - POSTGRES_PASSWORD=observationmanagementapi
      - POSTGRES_DB=observationmanagementapi_dev

volumes:
  postgres_data: